// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Message struct {
	ID             int64         `json:"id"`
	RoomID         int64         `json:"room_id"`
	ReplyMessageID sql.NullInt64 `json:"reply_message_id"`
	SenderID       int64         `json:"sender_id"`
	ModifiedAt     time.Time     `json:"modified_at"`
	CreatedAt      time.Time     `json:"created_at"`
	MessageText    string        `json:"message_text"`
}

type Room struct {
	ID        int64     `json:"id"`
	RoomName  string    `json:"room_name"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}

type UserRoom struct {
	UserID int64 `json:"user_id"`
	RoomID int64 `json:"room_id"`
}
